                                                                                                                                            /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tennis_club;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */ 
public class Coach extends javax.swing.JFrame {

    /**
     * Creates new form Coach
     */
    public Coach() {
        initComponents();
        load_to_table_coacher();
        lg.setText(login.db_user);
    }

     ArrayList<String> coacher_data_list = new ArrayList<String>();
    String User_Id = "";
    int select_id = 0;

    void load_to_table_coacher() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) coacher_table_2.getModel();
            dtm.setRowCount(0);

            Statement s = dbcon.dbConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM coach");

            while (rs.next()) {

                Vector v = new Vector();

                String id = rs.getString("Coach_Id");
                String name = rs.getString("Coach_name");
                String nic = rs.getString("NIC");
                String address = rs.getString("Coach_address");
                String contact = rs.getString("Coach_Contact");
                String email = rs.getString("Coach_email");
                String price = rs.getString("Privet_coach_price");
                coacher_data_list.add(id);

                v.add(name);
                v.add(nic);
                v.add(address);
                v.add(contact);
                v.add(email);
                v.add(price);
                dtm.addRow(v);

            }


        } catch (Exception e) {
            e.printStackTrace();
        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        lg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cnic = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        ccontact = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        cprice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        coacher_table_1 = new javax.swing.JTable();
        add_to_table_coacher = new javax.swing.JButton();
        clear_coacher = new javax.swing.JButton();
        SAVE_db_coacher = new javax.swing.JButton();
        update_save_coacher = new javax.swing.JButton();
        edit_user1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        coacher_table_2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Coach");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 180, 50));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lg.setBackground(new java.awt.Color(255, 255, 204));
        lg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 280, 30));

        jLabel3.setText("Coacher Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel19.setText("NIC");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel13.setText("Coacher Address");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel14.setText("Coacher Contact");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel15.setText("Coacher Email");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel16.setText("Privet Coach price");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 335, -1));

        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });
        jPanel1.add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 335, -1));

        caddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddressActionPerformed(evt);
            }
        });
        jPanel1.add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 335, -1));

        ccontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccontactActionPerformed(evt);
            }
        });
        jPanel1.add(ccontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 335, -1));
        jPanel1.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 335, -1));
        jPanel1.add(cprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 335, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Add Coacher");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 280, 40));

        coacher_table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coacher Name", "NIC", "Coacher Address", "Coacher Contact", "Coacher Email", "Private Coach price"
            }
        ));
        jScrollPane5.setViewportView(coacher_table_1);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 1110, 240));

        add_to_table_coacher.setText("Add to Table");
        add_to_table_coacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_to_table_coacherActionPerformed(evt);
            }
        });
        jPanel1.add(add_to_table_coacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        clear_coacher.setText("Clear");
        clear_coacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_coacherActionPerformed(evt);
            }
        });
        jPanel1.add(clear_coacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        SAVE_db_coacher.setText("Save to Db");
        SAVE_db_coacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_db_coacherActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE_db_coacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        update_save_coacher.setText("Update & Save");
        update_save_coacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_save_coacherActionPerformed(evt);
            }
        });
        jPanel1.add(update_save_coacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        edit_user1.setText("Edit");
        edit_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_user1ActionPerformed(evt);
            }
        });
        jPanel1.add(edit_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        coacher_table_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coacher Name", "NIC", "Coacher Address", "Coacher Contact", "Coacher Email", "Private Coach price"
            }
        ));
        jScrollPane4.setViewportView(coacher_table_2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 1710, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void caddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caddressActionPerformed

    private void ccontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccontactActionPerformed

    private void add_to_table_coacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_to_table_coacherActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) coacher_table_1.getModel();
            String name = cname.getText();
            String nic = cnic.getText();
            String address = caddress.getText();
            String contact = ccontact.getText();
            String email = cemail.getText();
            String price = cprice.getText();

            String data[] = {name, nic, address, contact, email, price};

            dtm.addRow(data);

            cname.setText("");
            cnic.setText("");
            caddress.setText("");
            ccontact.setText("");
            cemail.setText("");
            cprice.setText("");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_add_to_table_coacherActionPerformed

    private void clear_coacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_coacherActionPerformed
        cname.setText("");
        cnic.setText("");
        caddress.setText("");
        ccontact.setText("");
        cemail.setText("");
        cprice.setText("");
    }//GEN-LAST:event_clear_coacherActionPerformed

    private void SAVE_db_coacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVE_db_coacherActionPerformed
        try {
           String id = login.User_Id;
            DefaultTableModel dtm = (DefaultTableModel) coacher_table_1.getModel();

            for (int i = 0; i < dtm.getRowCount(); i++) {

                String name     = dtm.getValueAt(i, 0).toString();
                String nic      = dtm.getValueAt(i, 1).toString();
                String address  = dtm.getValueAt(i, 2).toString();
                String email    = dtm.getValueAt(i, 3).toString();
                String contact  = dtm.getValueAt(i, 4).toString();
                String price    = dtm.getValueAt(i, 5).toString();

                //String id = login.log_user;

                //System.out.println(id);
                Statement s = dbcon.dbConnection().createStatement();
                s.executeUpdate("INSERT INTO coach(Coach_name,NIC,Coach_address,Coach_Contact,Coach_email,Privet_coach_price,User_User_Id) VALUES ('" + name + "','" + nic + "','" + address + "','" + email + "','" + contact + "','" + price + "','" + id + "')");

            }
            dtm.setRowCount(0);
            JOptionPane.showMessageDialog(rootPane, "Sucessfully Saved to Database", "Sussess", JOptionPane.INFORMATION_MESSAGE);

            //coacher_data_list.clear();
           load_to_table_coacher();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SAVE_db_coacherActionPerformed

    private void update_save_coacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_save_coacherActionPerformed
           try {
            DefaultTableModel dtm = (DefaultTableModel) coacher_table_2.getModel();

            String name = cname.getText();
            String nic = cnic.getText();
            String address = caddress.getText();
            String contact = ccontact.getText();
            String email = cemail.getText();
            String price = cprice.getText();

            Statement s = dbcon.dbConnection().createStatement();
            s.executeUpdate("UPDATE Coach set Coach_name = '" + name + "',NIC = '" + nic + "',Coach_address = '" + address + "',Coach_Contact= '" + contact + "',Coach_email = '" + email + "',Privet_coach_price= '" + price + "' WHERE Coach_Id='" + User_Id + "' ");


            cname.setText("");
            cnic.setText("");
            caddress.setText("");
            ccontact.setText("");
            cemail.setText("");
            cprice.setText("");

            load_to_table_coacher();

            dtm.setRowCount(0);
            coacher_data_list.clear();

            load_to_table_coacher();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_update_save_coacherActionPerformed

    private void edit_user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_user1ActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) coacher_table_2.getModel();

            int i = coacher_table_2.getSelectedRow();
            User_Id = coacher_data_list.get(i);

            String name = dtm.getValueAt(i, 0).toString();
            String nic = dtm.getValueAt(i, 1).toString();
            String address = dtm.getValueAt(i, 2).toString();
            String email = dtm.getValueAt(i, 3).toString();
            String contact = dtm.getValueAt(i, 4).toString();
            String price = dtm.getValueAt(i, 5).toString();

            cname.setText(name);
            cnic.setText(nic);
            caddress.setText(address);
            ccontact.setText(contact);
            cemail.setText(email);
            cprice.setText(price);


            coacher_data_list.clear();
            load_to_table_coacher();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_edit_user1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Coach().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVE_db_coacher;
    private javax.swing.JButton add_to_table_coacher;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField ccontact;
    private javax.swing.JTextField cemail;
    private javax.swing.JButton clear_coacher;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnic;
    private javax.swing.JTable coacher_table_1;
    private javax.swing.JTable coacher_table_2;
    private javax.swing.JTextField cprice;
    private javax.swing.JButton edit_user1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lg;
    private javax.swing.JButton update_save_coacher;
    // End of variables declaration//GEN-END:variables
}
