/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tennis_club;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import sun.net.www.content.audio.x_aiff;

/**
 *
 * @author ASUS
 */
public class Players extends javax.swing.JFrame {

    /**
     * Creates new form Player
     */
    public Players() {
        initComponents();
        //load_to_cmd();
        lg.setText(login.db_user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        cmb_plan = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        l9 = new javax.swing.JLabel();
        clear_coacher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Player");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Player");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 290, 50));

        lg.setBackground(new java.awt.Color(255, 255, 204));
        lg.setText(" ");
        lg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 20, 280, 30));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        l1.setText("NIC");
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        l2.setText("Age");
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        l3.setText("Address");
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        l4.setText("Contact_Number");
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 418, -1));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 418, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 418, -1));
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 418, -1));

        l5.setText("Email");
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        l6.setText("Coaching plan");
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        l7.setText("Weight");
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        l8.setText("Coaching Hours");
        jPanel1.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 418, -1));
        jPanel1.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 418, -1));
        jPanel1.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 418, -1));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        cmb_plan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Annual", "6 Month ", "3 Month", "1 Month" }));
        cmb_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_planActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, -1));

        playerT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Nic", "Age", "Address", "Contact Number", "Email", "Coaching Plan", "Weight", "Coaching Hours"
            }
        ));
        jScrollPane1.setViewportView(playerT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 1720, 370));

        jButton1.setText("Plans");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 150, -1));
        jPanel1.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 418, -1));

        l9.setText("Name");
        jPanel1.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        clear_coacher.setText("Clear");
        clear_coacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_coacherActionPerformed(evt);
            }
        });
        jPanel1.add(clear_coacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<String> player_data_list = new ArrayList<String>();
    String uid = "";
    int select_id = 0;

    public void load_to_cmd() {
        try {
            Statement s = dbcon.dbConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT *FROM Player");
            
            while (rs.next()) {
                 Vector v = new Vector();// example vector kiynne malu dalak wage ekak.muhude inna malu alla ganna dana malu dalak wag
                String a = rs.getString("Player_Name");
                String i = rs.getString("Player_nic");
                String b = rs.getString("Player_Age");
                String c = rs.getString("Player_Address");
                String d = rs.getString("Player_Contact_Number");
                String e = rs.getString("Player_Email");
                String f = rs.getString("Coaching_plan");
                String g = rs.getString("Weight");
                String h = rs.getString("Coaching_hours");
                
                String id = rs.getString(select_id);
                
                v.add(a);
                v.add(i);
                v.add(b);
                v.add(c);
                v.add(d);
                v.add(e);
                v.add(f);
                v.add(g);
                v.add(h);
                v.add(id);
                
                

                System.out.println(a);
                cmb_plan.setModel(new DefaultComboBoxModel(v)); //ape drop down eka ape bottuwe malu dana box eka wage
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try {

            /*
             * int id = login.log_id; DefaultTableModel dtm =
             * (DefaultTableModel) playerT.getModel();4
             *
             * for (int i = 0; 1 < dtm.getRowCount(); i++) {
             *
             * String name = dtm.getValueAt(i, 0).toString(); String age =
             * dtm.getValueAt(i, 1).toString(); String address =
             * dtm.getValueAt(i, 2).toString(); String con = dtm.getValueAt(i,
             * 3).toString(); String email = dtm.getValueAt(i, 4).toString();
             * String coaching_plan = dtm.getValueAt(i, 5).toString(); String
             * weight = dtm.getValueAt(i, 6).toString(); String coaching_hours =
             * dtm.getValueAt(i, 7).toString();
             */

            String a = t1.getText();
            String i = t6.getText();
            String b = t2.getText();
            String c = t3.getText();
            String d = t4.getText();
            String e = t5.getText();
            String f = cmb_plan.getSelectedItem().toString();
            String g = t7.getText();
            String h = t8.getText();
            String id = login.User_Id;
            // String idi =Membership_plan.memberplanid;
            //String idi = cmb_plan.getSelectedItem().toString();

            //System.out.println(id);
            //System.out.println(idi);
            Statement s = dbcon.dbConnection().createStatement();
            s.executeUpdate("INSERT INTO player(Player_Name,Player_nic,Player_Age,Player_Address,Player_Contact_Number,Player_Email,Coaching_plan,Weight,Coaching_hours,User_User_Id,)VALUES"
                    + "('" + a + "','" + i + "','" + b + "','" + c + "','" + d + "','" + e + "','" + f + "','" + g + "','" + h + "','" + id + "')");


            //player_data_list();


        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_SaveActionPerformed

    private void cmb_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_planActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_planActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Membership_plan mp = new Membership_plan();
        mp.setVisible(true);
        //this.dispose();
        //System.gc();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clear_coacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_coacherActionPerformed
        t1.setText("");
        t2.setText("");
        t6.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        cmb_plan.setSelectedItem("");
        t7.setText("");
        t8.setText("");

    }//GEN-LAST:event_clear_coacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Players.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Players().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton Save;
    private javax.swing.JButton clear_coacher;
    private javax.swing.JComboBox cmb_plan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel lg;
    private javax.swing.JTable playerT;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
