/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tennis_club;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Reprot extends javax.swing.JFrame {

    /**
     * Creates new form Reprot
     */
    public Reprot() {
        initComponents();
        lg.setText(login.db_user);
        getcoachreport();
        getplayerreport();
        
    }
    public static String getcoachreport_id = "";
    void getcoachreport(){
        try {
            DefaultTableModel dtm = (DefaultTableModel) getcoachreport.getModel();
            dtm.setRowCount(0);

            Statement s = dbcon.dbConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT Coach_Id,Coach_name FROM coach");
             while (rs.next()) {                
                Vector v = new Vector();
                String id = rs.getString("Coach_Id");
                String name = rs.getString("Coach_name");
                
                v.add(id);
                v.add(name);
                dtm.addRow(v);
            }      
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void getplayerreport(){
        try {
            DefaultTableModel dtm = (DefaultTableModel) palyerreport.getModel();
            dtm.setRowCount(0);

            Statement s = dbcon.dbConnection().createStatement();
            ResultSet rs = s.executeQuery("SELECT Player_Id,Player_Name FROM player");
             while (rs.next()) {                
                Vector v = new Vector();
                String id = rs.getString("Player_Id");
                String name = rs.getString("Player_Name");
                
                v.add(id);
                v.add(name);
                dtm.addRow(v);
            }
                    
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        palyerreport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        getcoachreport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setBackground(new java.awt.Color(255, 255, 204));
        lg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 280, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Report");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, 50));

        jButton9.setText("Home");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 730, -1, -1));

        palyerreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player ID", "Name"
            }
        ));
        palyerreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palyerreportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(palyerreport);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 730, 250));

        getcoachreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coach ID", "Coach name"
            }
        ));
        getcoachreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getcoachreportMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(getcoachreport);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 730, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Player");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Coach");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void getcoachreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getcoachreportMouseClicked
        try {
            Coach_report chreport = new Coach_report();
            chreport.setVisible(true);
            DefaultTableModel dtm = (DefaultTableModel) getcoachreport.getModel();
            int selectedr = getcoachreport.getSelectedRow();
            getcoachreport_id = dtm.getValueAt(selectedr, 0).toString();
            
           // System.out.println(getcoachreport_id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_getcoachreportMouseClicked
public static String getplayerreport_id = "";
    private void palyerreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palyerreportMouseClicked
        Player_report chreport = new Player_report();
        chreport.setVisible(true);
        DefaultTableModel dtm = (DefaultTableModel) palyerreport.getModel();
        int selectedrow = palyerreport.getSelectedRow();
        getplayerreport_id = dtm.getValueAt(selectedrow,0).toString();
        
    }//GEN-LAST:event_palyerreportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reprot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reprot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reprot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reprot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reprot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable getcoachreport;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lg;
    private javax.swing.JTable palyerreport;
    // End of variables declaration//GEN-END:variables
}
